import { jsPDF } from 'jspdf'
import Papa from 'papaparse'
import { Goal, Task, Habit } from '../types'
import { UserActivityService } from './userActivityService'

export class ExportService {
  /**
   * Export goals and tasks to PDF
   */
  static async exportToPDF(
    userId: string,
    goals: Goal[],
    userEmail: string
  ): Promise<void> {
    try {
      const doc = new jsPDF()
      const pageWidth = doc.internal.pageSize.getWidth()
      const pageHeight = doc.internal.pageSize.getHeight()
      let yPosition = 20

      // Helper to add new page if needed
      const checkNewPage = (requiredSpace: number) => {
        if (yPosition + requiredSpace > pageHeight - 20) {
          doc.addPage()
          yPosition = 20
        }
      }

      // Title
      doc.setFontSize(24)
      doc.setTextColor(66, 66, 66)
      doc.text('Goals Tracker Report', pageWidth / 2, yPosition, { align: 'center' })
      
      yPosition += 10
      doc.setFontSize(10)
      doc.setTextColor(128, 128, 128)
      doc.text(`User: ${userEmail}`, pageWidth / 2, yPosition, { align: 'center' })
      
      yPosition += 5
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' })
      
      // Get user statistics
      const stats = await UserActivityService.getActivityStats(userId)
      
      yPosition += 15
      checkNewPage(40)
      
      // Statistics Summary
      doc.setFontSize(16)
      doc.setTextColor(59, 130, 246) // Blue color
      doc.text('Summary Statistics', 20, yPosition)
      
      yPosition += 10
      doc.setFontSize(10)
      doc.setTextColor(66, 66, 66)
      
      const statsText = [
        `Total Goals: ${goals.length}`,
        `Completed Goals: ${stats.totalGoalsCompleted}`,
        `Completed Tasks: ${stats.totalTasksCompleted}`,
        `Completed Habits: ${stats.totalHabitsCompleted}`,
        `Current Streak: ${stats.currentStreak} days`,
        `Best Streak: ${stats.bestStreak} days`,
        `Active Days: ${stats.totalActiveDays}`
      ]
      
      statsText.forEach(text => {
        doc.text(text, 20, yPosition)
        yPosition += 6
      })
      
      // Goals Section
      yPosition += 10
      checkNewPage(50)
      
      doc.setFontSize(16)
      doc.setTextColor(59, 130, 246)
      doc.text('Goals Details', 20, yPosition)
      yPosition += 10
      
      // Process each goal
      goals.forEach((goal, index) => {
        checkNewPage(50)
        
        // Goal header
        doc.setFontSize(12)
        doc.setTextColor(66, 66, 66)
        doc.setFont(undefined, 'bold')
        doc.text(`${index + 1}. ${goal.title}`, 20, yPosition)
        yPosition += 6
        
        // Goal description
        doc.setFontSize(9)
        doc.setFont(undefined, 'normal')
        doc.setTextColor(128, 128, 128)
        if (goal.description) {
          const descLines = doc.splitTextToSize(goal.description, pageWidth - 40)
          descLines.forEach((line: string) => {
            checkNewPage(6)
            doc.text(line, 25, yPosition)
            yPosition += 5
          })
        }
        
        yPosition += 3
        
        // Goal metadata
        doc.setTextColor(100, 100, 100)
        doc.text(`Category: ${goal.category || 'Personal'} | Deadline: ${goal.deadline || 'Not set'}`, 25, yPosition)
        yPosition += 6
        
        // Tasks progress
        const completedTasks = goal.tasks.filter(t => t.isComplete).length
        const totalTasks = goal.tasks.length
        const progress = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0
        
        doc.setTextColor(34, 197, 94) // Green color
        doc.text(`Progress: ${completedTasks}/${totalTasks} tasks (${progress}%)`, 25, yPosition)
        yPosition += 8
        
        // Tasks list
        if (goal.tasks.length > 0) {
          doc.setFontSize(8)
          doc.setTextColor(80, 80, 80)
          doc.text('Tasks:', 25, yPosition)
          yPosition += 5
          
          goal.tasks.forEach((task: Task) => {
            checkNewPage(6)
            const status = task.isComplete ? '[x]' : '[ ]'
            const taskText = `${status} ${task.text}`
            const lines = doc.splitTextToSize(taskText, pageWidth - 60)
            
            lines.forEach((line: string) => {
              checkNewPage(5)
              doc.text(line, 30, yPosition)
              yPosition += 4
            })
          })
        }
        
        yPosition += 6
      })
      
      // Footer on last page
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(
        'Generated by Goals Tracker App',
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      )
      
      // Save the PDF
      const filename = `goals-report-${new Date().toISOString().split('T')[0]}.pdf`
      doc.save(filename)
    } catch (error) {
      console.error('Error generating PDF:', error)
      throw new Error('Failed to generate PDF report')
    }
  }

  /**
   * Export goals to CSV
   */
  static exportGoalsToCSV(goals: Goal[]): void {
    try {
      const csvData = goals.map(goal => {
        const completedTasks = goal.tasks.filter(t => t.isComplete).length
        const totalTasks = goal.tasks.length
        const progress = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0
        
        return {
          'Goal Title': goal.title,
          'Description': goal.description || '',
          'Category': goal.category || 'Personal',
          'Deadline': goal.deadline || '',
          'Total Tasks': totalTasks,
          'Completed Tasks': completedTasks,
          'Progress (%)': progress,
          'Status': goal.status || 'active',
          'Created Date': goal.created_at ? new Date(goal.created_at).toLocaleDateString() : ''
        }
      })
      
      const csv = Papa.unparse(csvData)
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      const url = URL.createObjectURL(blob)
      
      link.setAttribute('href', url)
      link.setAttribute('download', `goals-export-${new Date().toISOString().split('T')[0]}.csv`)
      link.style.visibility = 'hidden'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } catch (error) {
      console.error('Error generating CSV:', error)
      throw new Error('Failed to generate CSV export')
    }
  }

  /**
   * Export tasks to CSV
   */
  static exportTasksToCSV(goals: Goal[]): void {
    try {
      const allTasks = goals.flatMap(goal => 
        goal.tasks.map((task: Task) => ({
          'Goal': goal.title,
          'Task': task.text,
          'Due Date': task.dueDate || task.due_date || '',
          'Priority': task.priority || 'medium',
          'Category': task.category || '',
          'Status': task.isComplete || task.is_complete ? 'Completed' : 'Pending',
          'Created Date': task.created_at ? new Date(task.created_at).toLocaleDateString() : ''
        }))
      )
      
      const csv = Papa.unparse(allTasks)
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      const url = URL.createObjectURL(blob)
      
      link.setAttribute('href', url)
      link.setAttribute('download', `tasks-export-${new Date().toISOString().split('T')[0]}.csv`)
      link.style.visibility = 'hidden'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } catch (error) {
      console.error('Error generating tasks CSV:', error)
      throw new Error('Failed to generate tasks CSV export')
    }
  }

  /**
   * Export user activity data to CSV
   */
  static async exportActivityToCSV(userId: string): Promise<void> {
    try {
      const stats = await UserActivityService.getActivityStats(userId)
      
      const csvData = stats.recentActivity.map(activity => ({
        'Date': new Date(activity.activity_date).toLocaleDateString(),
        'Goals Completed': activity.goals_completed_count,
        'Tasks Completed': activity.tasks_completed_count,
        'Habits Completed': activity.habits_completed_count
      }))
      
      const csv = Papa.unparse(csvData)
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      const url = URL.createObjectURL(blob)
      
      link.setAttribute('href', url)
      link.setAttribute('download', `activity-export-${new Date().toISOString().split('T')[0]}.csv`)
      link.style.visibility = 'hidden'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } catch (error) {
      console.error('Error generating activity CSV:', error)
      throw new Error('Failed to generate activity CSV export')
    }
  }
}
